In [1]:
3+4

ans =  7


In [2]:
(- 9) + (+ 4) + (- 6) + (+ 3)

ans = -8


In [3]:
3/2

ans =  1.5000


In [4]:
3/4

ans =  0.75000


In [5]:
1/2 < 10

ans = 1


In [6]:
2*(3/4)

ans =  1.5000


In [7]:
11/4

ans =  2.7500


In [8]:
2*3/4

ans =  1.5000


In [9]:
2+3/4

ans =  2.7500


In [10]:
(7+1/9)

ans =  7.1111


In [11]:
rats(7.1111)

ans =      64/9


In [12]:
rats(hilb(2))

ans =

          1        1/2
        1/2        1/3



In [13]:
rats(2+3/4)

ans =      11/4


In [14]:
rats(5+3/7)

ans =      38/7


In [15]:
rats(11/3)

ans =      11/3


In [16]:
rat(11/3)

ans = 4 + 1/(-3)


In [17]:
rats(3+2/3)

ans =      11/3


In [18]:
rats(7+3/4)

ans =      31/4


In [19]:
rem(25,4)

ans =  1


In [20]:
rem(4,17)

ans =  4


In [21]:
rem(17,4)

ans =  1


In [22]:
rem(11,3)

ans =  2


In [23]:
rats(5/6 - 3/4)

ans =      1/12


In [24]:
lcm(4,6)

ans =  12


In [25]:
gcd(36,24)

ans =  12


In [26]:
lcm(36,24)

ans =  72


In [27]:
lookfor cos

acos                Compute the inverse cosine in radians for each element of X
                    .
acosh               Compute the inverse hyperbolic cosine for each element of X
                    .
cos                 Compute the cosine for each element of X in radians.
cosh                Compute the hyperbolic cosine for each element of X.
acosd               Compute the inverse cosine in degrees for each element of X
                    .
acsc                Compute the inverse cosecant in radians for each element of
                    X.
acscd               Compute the inverse cosecant in degrees for each element of
                    X.
acsch               Compute the inverse hyperbolic cosecant of each element of 
                    X.
cosd                Compute the cosine for each element of X in degrees.
csc                 Compute the cosecant for each element of X in radians.
cscd                Compute the cosecant for each element of X in degrees.
csch            

In [28]:
a=3

a =  3


In [29]:
a

a =  3


In [30]:
b

error: 'b' undefined near line 1 column 1


In [31]:
b=(1+3)/2

b =  2


In [32]:
c=b

c =  2


In [33]:
d=b+1

d =  3


In [34]:
a=a+1

a =  4


In [35]:
a=a+1

a =  5


In [36]:
whos

Variables in the current scope:

   Attr Name        Size                     Bytes  Class
   ==== ====        ====                     =====  ===== 
        a           1x1                          8  double
        ans         1x1                          8  double
        b           1x1                          8  double
        c           1x1                          8  double
        d           1x1                          8  double

Total is 5 elements using 40 bytes



In [37]:
who

Variables in the current scope:

a    ans  b    c    d



In [38]:
clear a

In [39]:
who

Variables in the current scope:

ans  b    c    d



In [40]:
clear c d

In [41]:
who

Variables in the current scope:

ans  b



In [42]:
abc='Heramb'

abc = Heramb


In [43]:
abc

abc = Heramb


# Vectors

##  Vector

In [3]:
a= [1,2,3,4]

a =

   1   2   3   4



In [4]:
a'

ans =

   1
   2
   3
   4



In [46]:
b=[1:8]

b =

   1   2   3   4   5   6   7   8



In [47]:
b'

ans =

   1
   2
   3
   4
   5
   6
   7
   8



In [48]:
c=[[1:5],[4:6]]

c =

   1   2   3   4   5   4   5   6



In [49]:
c'

ans =

   1
   2
   3
   4
   5
   4
   5
   6



In [50]:
a=[3 4 5 6]

a =

   3   4   5   6



In [51]:
t = -[3 4 5 6 7 8 9 0 ]

t =

  -3  -4  -5  -6  -7  -8  -9  -0



In [52]:
t = -[3 4 5 6 7 8 9 -0 ]

t =

  -3  -4  -5  -6  -7  -8  -9   0



In [53]:
t(5)

ans = -7


In [54]:
t([5])

ans = -7


In [55]:
t(5)=10

t =

   -3   -4   -5   -6   10   -8   -9    0



In [56]:
t([1 4])=[6 7]

t =

    6   -4   -5    7   10   -8   -9    0



In [57]:
h=(1:20)

h =

 Columns 1 through 16:

    1    2    3    4    5    6    7    8    9   10   11   12   13   14   15   16

 Columns 17 through 20:

   17   18   19   20



In [58]:
d=(1:5:100)

d =

 Columns 1 through 16:

    1    6   11   16   21   26   31   36   41   46   51   56   61   66   71   76

 Columns 17 through 20:

   81   86   91   96



In [59]:
s=(40:-1:-40)

s =

 Columns 1 through 16:

   40   39   38   37   36   35   34   33   32   31   30   29   28   27   26   25

 Columns 17 through 32:

   24   23   22   21   20   19   18   17   16   15   14   13   12   11   10    9

 Columns 33 through 48:

    8    7    6    5    4    3    2    1    0   -1   -2   -3   -4   -5   -6   -7

 Columns 49 through 64:

   -8   -9  -10  -11  -12  -13  -14  -15  -16  -17  -18  -19  -20  -21  -22  -23

 Columns 65 through 80:

  -24  -25  -26  -27  -28  -29  -30  -31  -32  -33  -34  -35  -36  -37  -38  -39

 Column 81:

  -40



In [60]:
gcd([15 9],[20 18])

ans =

   5   9



In [61]:
lcm([15 20],[12 14])

ans =

    60   140



In [62]:
lcm(15 20)

parse error:

  syntax error

>>> lcm(15 20)
            ^



In [63]:
lcm(15, 20)

ans =  60


In [64]:
typeinfo('abc')

ans = sq_string


In [65]:
typeinfo(a)

ans = matrix


In [66]:
type(a)

error: type: input arguments must be strings
error: called from
    type at line 40 column 5


In [67]:
type(abc)

error: type: 'Heramb' undefined


In [68]:
typeinfo('a')

ans = sq_string


In [69]:
type('a')

a is a variable
   3   4   5   6



In [70]:
type('b')

b is a variable
   1   2   3   4   5   6   7   8



In [71]:
who

Variables in the current scope:

a    abc  ans  b    c    d    h    s    t



In [72]:
typeinfo('t')

ans = sq_string


In [73]:
type('t')

t is a variable
    6   -4   -5    7   10   -8   -9    0



In [74]:
z=I

z =  0 + 1i


In [75]:
I

ans =  0 + 1i


In [76]:
2i + 3i

ans =  0 + 5i


In [77]:
AA = balance(A)

error: 'A' undefined near line 1 column 14


In [78]:
balance(a)

error: balance: A must be a square matrix


In [79]:
matrix_type(z)

ans = Diagonal


In [80]:
matrix_type(b)

ans = Rectangular


In [81]:
matrix_type(a)

ans = Rectangular


In [82]:
matrix_type(d)

error: octave_base_value::matrix_type (): wrong type argument 'range'


In [83]:
a

a =

   3   4   5   6



In [84]:
mean(a)

ans =  4.5000


In [85]:
b=[1 2 3 3 3 6 7 8]

b =

   1   2   3   3   3   6   7   8



In [86]:
mean(b)

ans =  4.1250


In [87]:
mode(b)

ans =  3


In [88]:
median(b)

ans =  3


In [89]:
meansq(b)

ans =  22.625


In [90]:
b^2

error: for x^y, only square matrix arguments are permitted and one argument must be scalar.  Use .^ for elementwise power.


In [91]:
b**2

error: for x^y, only square matrix arguments are permitted and one argument must be scalar.  Use .^ for elementwise power.


In [92]:
sqrt(b)

ans =

   1.0000   1.4142   1.7321   1.7321   1.7321   2.4495   2.6458   2.8284



In [93]:
mean(b)^2

ans =  17.016


In [94]:
a=([2:2:20])'

a =

    2
    4
    6
    8
   10
   12
   14
   16
   18
   20



In [95]:
a=0:5

a =

   0   1   2   3   4   5



In [96]:
linspace(1,5,9)

ans =

 Columns 1 through 8:

   1.0000   1.5000   2.0000   2.5000   3.0000   3.5000   4.0000   4.5000

 Column 9:

   5.0000



In [97]:
k=([2:2:20];[3:3:30])'

parse error:

  syntax error

>>> k=([2:2:20];[3:3:30])'
               ^



In [98]:
l=[1;2;3;5;6;7]

l =

   1
   2
   3
   5
   6
   7



In [99]:
n=([1:10;11:20])

n =

    1    2    3    4    5    6    7    8    9   10
   11   12   13   14   15   16   17   18   19   20



In [100]:
e=[2:2:20;3:3:30;4:4:40;5:5:50;6:6:60;7:7:70;8:8:80;9:9:90;10:10:100]'

e =

     2     3     4     5     6     7     8     9    10
     4     6     8    10    12    14    16    18    20
     6     9    12    15    18    21    24    27    30
     8    12    16    20    24    28    32    36    40
    10    15    20    25    30    35    40    45    50
    12    18    24    30    36    42    48    54    60
    14    21    28    35    42    49    56    63    70
    16    24    32    40    48    56    64    72    80
    18    27    36    45    54    63    72    81    90
    20    30    40    50    60    70    80    90   100



In [102]:
typeinfo('bbbv')

ans = sq_string


In [103]:
typeinfo(e)

ans = sq_string


## Matrix

In [104]:
A=[1 2 3; 4 5 6; 7 8 9]

A =

   1   2   3
   4   5   6
   7   8   9



In [105]:
B=A'

B =

   1   4   7
   2   5   8
   3   6   9



In [106]:
A*B

ans =

    14    32    50
    32    77   122
    50   122   194



In [107]:
A*A'

ans =

    14    32    50
    32    77   122
    50   122   194



In [108]:
A/2

ans =

   0.50000   1.00000   1.50000
   2.00000   2.50000   3.00000
   3.50000   4.00000   4.50000



In [109]:
sqrt(B)

ans =

   1.0000   2.0000   2.6458
   1.4142   2.2361   2.8284
   1.7321   2.4495   3.0000



In [110]:
A

A =

   1   2   3
   4   5   6
   7   8   9



In [111]:
A^2

ans =

    30    36    42
    66    81    96
   102   126   150



In [112]:
f=[1,2,3;4,5,6]

f =

   1   2   3
   4   5   6



In [113]:
f^2

error: for x^y, only square matrix arguments are permitted and one argument must be scalar.  Use .^ for elementwise power.


In [114]:
f.^2

ans =

    1    4    9
   16   25   36



In [115]:
A.^2

ans =

    1    4    9
   16   25   36
   49   64   81



In [116]:
A

A =

   1   2   3
   4   5   6
   7   8   9



In [117]:
A(3,2)

ans =  8


In [118]:
A(2,1)

ans =  4


In [119]:
A(:,3)

ans =

   3
   6
   9



In [120]:
A(:,:)

ans =

   1   2   3
   4   5   6
   7   8   9



In [121]:
H=eye(3)

H =

Diagonal Matrix

   1   0   0
   0   1   0
   0   0   1



In [122]:
J= ones(3)

J =

   1   1   1
   1   1   1
   1   1   1



In [123]:
S= zeros(3)

S =

   0   0   0
   0   0   0
   0   0   0



In [124]:
J.*J'

ans =

   1   1   1
   1   1   1
   1   1   1



In [125]:
Q=rand(5)

Q =

   0.378173   0.130685   0.684611   0.253349   0.900784
   0.757607   0.337828   0.049712   0.185985   0.918407
   0.766332   0.504100   0.342613   0.012787   0.694400
   0.211188   0.786182   0.820417   0.850785   0.836419
   0.513634   0.435339   0.272011   0.015656   0.570081



In [126]:
Q= rand(3,4)

Q =

   0.652089   0.146750   0.297911   0.116607
   0.901097   0.903829   0.085085   0.479525
   0.758221   0.348809   0.651624   0.937947



In [127]:
X=1:12

X =

    1    2    3    4    5    6    7    8    9   10   11   12



In [128]:
D= reshape(X,3,4)

D =

    1    4    7   10
    2    5    8   11
    3    6    9   12



In [129]:
F=[A D]

F =

    1    2    3    1    4    7   10
    4    5    6    2    5    8   11
    7    8    9    3    6    9   12



In [130]:
F=[A;D]

error: vertical dimensions mismatch (3x3 vs 3x4)


In [131]:
F=[A D]'

F =

    1    4    7
    2    5    8
    3    6    9
    1    2    3
    4    5    6
    7    8    9
   10   11   12



In [132]:
size(A)

ans =

   3   3



In [133]:
size(D)

ans =

   3   4



In [134]:
sizeof(A)

ans =  72


In [135]:
sizeof(D)

ans =  96


In [136]:
[row col] = size(A)

row =  3
col =  3


In [137]:
length(A)

ans =  3


In [138]:
length(D)

ans =  4


## Matrix Operations

In [139]:
O= rand(3)

O =

   0.464131   0.547530   0.481607
   0.332699   0.533402   0.038168
   0.588317   0.188266   0.897480



In [140]:
P=rand(3)

P =

   0.646071   0.649332   0.036123
   0.967407   0.835377   0.734608
   0.634559   0.141855   0.641407



In [141]:
O + P

ans =

   1.11020   1.19686   0.51773
   1.30011   1.36878   0.77278
   1.22288   0.33012   1.53889



In [145]:
W = A*D

W =

    14    32    50    68
    32    77   122   167
    50   122   194   266



In [146]:
R = D*A

error: operator *: nonconformant arguments (op1 is 3x4, op2 is 3x3)


In [147]:
R = D.*A

error: product: nonconformant arguments (op1 is 3x4, op2 is 3x3)


In [148]:
R = D.^2

R =

     1    16    49   100
     4    25    64   121
     9    36    81   144



### Random numbers

In [150]:
u= rand(2,3)

u =

   0.905623   0.922745   0.374664
   0.822000   0.647796   0.041979



In [151]:
u= 2* rand(2,3)

u =

   1.44195   1.59706   1.17179
   1.12246   0.77167   0.55613



In [152]:
u= 4*rand(2,3)

u =

   0.73751   2.78714   3.91418
   0.56341   0.46659   2.85525



In [160]:
u= 10*rand(2,3)+2

u =

   8.5734   6.2859   7.8218
   4.2427   4.2242   3.3692



In [161]:
u= 10*rand(2,3)-2

u =

   5.752271  -1.371654   3.618183
   6.503349   0.019443   7.284319



In [4]:
s = [3 -5 4]

s =

   3  -5   4



In [5]:
d = [1 2 5]'

d =

   1
   2
   5



In [6]:
s*d

ans =  13


In [7]:
A = [4 3; 6 9]

A =

   4   3
   6   9



In [8]:
B = [-2 9; -5 2]

B =

  -2   9
  -5   2



In [9]:
A - B

ans =

    6   -6
   11    7



In [10]:
x = [2 7 4 1]'

x =

   2
   7
   4
   1



In [11]:
1/2 * x

ans =

   1.00000
   3.50000
   2.00000
   0.50000



In [15]:
u = [-3 4 3]

u =

  -3   4   3



In [17]:
v = [3 1 5]'

v =

   3
   1
   5



In [18]:
u * v

ans =  10
